// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_3_Columns_to_Inspection_TypeInspection_and_1_col_to_SmPrice_MS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_3_Columns_to_Inspection_TypeInspection_and_1_col_to_SmPrice_MS));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241532150_Add_3_Columns_to_Inspection_TypeInspection_and_1_col_to_SmPrice_MS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
