// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adding_SMLocId_and_ShelfLocId_Fields_to_the_Location_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_SMLocId_and_ShelfLocId_Fields_to_the_Location_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202101291308285_Adding_SMLocId_and_ShelfLocId_Fields_to_the_Location_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
